// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var warnContainer = "\n  <div style=\'cursor: pointer; padding:10px; margin:15px 0; border-radius: 8px; height:18px; background:#F0E68C;\'>\n    <img src=\"" + chrome.extension.getURL("resources/logo19.png") + "\" style=\'float:left\'>\n    <div style=\'margin:2px 0 0 30px;\'>\n      conte&uacute;do bloqueado pela extens&atilde;o NoBBB, clique para ver \n    </div>\n  </div>\n  ";

var textPattern = /bbb|big ?brother|boninho|paredao|estalecas|leifert|casa ? de ?vidro/gi;

function isMatch(element) {
  var dataSet = element.target.dataset;
  if (dataSet === undefined) {
    return false;
  }
  var str = dataSet.pagelet;
  if (str !== undefined && str.startsWith("FeedUnit_")) {
    var match = element.target.innerText.match(textPattern);
    return match !== null;
  } else {
    return false;
  }
}

function show(element) {
  element.target.innerHTML = element.originalContent;
  return element.target.removeEventListener("click", (function (param) {
                return show(element);
              }));
}

function nodeInsertedHandler(element) {
  if (isMatch(element)) {
    element.originalContent = element.target.innerHTML;
    element.target.addEventListener("click", (function (param) {
            return show(element);
          }));
    element.target.innerHTML = warnContainer;
    return ;
  }
  
}

document.querySelector("[role='feed']").addEventListener("DOMNodeInserted", nodeInsertedHandler);

/* warnContainer Not a pure module */
